name: IsBuilder
version: 0.1
description: Fortgeschrittene Skyblock Rezepte
author: Darkluke1111
main: me.darkluke1111.isBuilder.IsBuilder

commands:
  openInv:
    description: test
    usage: \<command>

permissions: